### ISSUE TITLE
How to change MAX_NUMBER_OF_COLUMNS

### ISSUE THREAD

**Issue by drm7369** [antoinejaussoin/retro-board#188]
Hey, I want to change the variable MAX_NUMBER_OF_COLUMNS from 5 to 12. What would be the easiest method of going about this? I think the only way I can do this is to recompile/rebuild the docker images right? I tried to find the location of the TemplateEditor.tsx within the docker images so that maybe I could use a volume to overwrite the file during run because that seemed like the path of least resistance. But that didn't pan out because I couldnt find it in any of the docker images. Now im trying to rebuild it after making that change and I keep getting errors and its just not working. Do you see anything I might be missing / doing wrong? Full disclosure, I am not a developer but am pretty technical. Main problem is that I've never used any of these technologies before so its a bit over my head. Any help would be greatly appreciated. Thanks!!

**Packer Versions**
```
OS: Ubuntu 18.04.5 LTS
YARN: 1.22.5
Docker: 19.03.14
docker-compose: 1.25.4
nodejs: v15.3.0.
```

**Clone repo**
`git clone https://github.com/antoinejaussoin/retro-board.git -b master`

**Install Yarn**
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn
export PATH="$PATH:`yarn global bin`"
```

**Install Nodejs**
```
curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Start Postgres, Redis, PGAdmin** 
**_Question -  The instructions refer to a .dev directory but i cannot find any. Is this generated by a command that im not running??_**
_I am using this Dockerfile as a replacement but sure if this is correct_

```
version: '3'
services:
  redis:
    image: redis:latest
    depends_on:
      - postgres
    restart: unless-stopped
    network_mode: host
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  postgres:
    image: postgres:11.6
    hostname: postgres
    environment:
      POSTGRES_USER: postgres # Must be the same as DB_USER below
      POSTGRES_PASSWORD: postgres # Must be the same as DB_PASSWORD below
      POSTGRES_DB: retroboard # Must be the same as DB_NAME below
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: host
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  pgadmin:
    image: dpage/pgadmin4:4.15 # use biarms/pgadmin4 on ARM
    depends_on:
      - postgres
    ports:
      - '8080:80' # Change 8080 to whatever port you want to access pgAdmin from
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@retrospected.com # Can be anything
      PGADMIN_DEFAULT_PASSWORD: admin # Please change this!
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    network_mode: host
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

volumes:
  database:
  pgadmin:
```

**Installing dependencies and trying to start everything**
```
cd retro-board
sudo make install
sudo yarn
sudo yarn upgrade
sudo npx browserslist --update-db
sudo yarn start-ui
sudo yarn start-server
```
